# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b9042336c30abe91890bc497b7d434ef4a8eb213bc6df363d279ad4139b37d2bd20281666d70ac4f79f2abc51d6dc86af9f5751fb6615e76c33568dd9b25bd59

test:
  secret_key_base: 2b01c3189e95b4484b2c7ad5c050b2166f7c5dcff20f4bbfee76965d24a7a1cf84bf3836aff2eede934bee0f7c842e6c6e68ed866fe46530800a4ab65a651d1c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
